---
- hosts: all
  tasks:
    - name: install apache2 on Ubuntu
      apt: name=apache2 update_cache=yes state=latest
      become: yes
      when: ansible_distribution == "Ubuntu"
    - name: install njinx on RedHat
      yum: name=nginx state=latest
      become: yes
      when: ansible_distribution == "RedHat"
