- hosts: localhost
  name: create ec2 user
  tasks:
          - name: create ec2 user
            iam:
                    iam_type: user
                    name: jenkinstest
                    state: present
                    password: Passw0rd
                    access_key_state: create
